# Site settings
title: SWJTU-Leeds Joint School 课程经验库
description: 整理并分享西南交通大学 - 利兹联合学院各门课程的学习经验、准备建议与评价。

# 网站基础路径和网址
baseurl: "/SWJTU-Leeds-Joint-School"  # 仓库名
url: "https://lhannnn.github.io"      # 你 GitHub Pages 的基础 URL

# 学校信息
schoolname: "SWJTU-Leeds Joint School"
schoolurl: "https://leeds.swjtu.edu.cn/"
twitter_username: ""  # 不用就留空

# 地址（可选）
address: |
    SWJTU-Leeds Joint School  
    Southwest Jiaotong University  
    University of Leeds

# Google Analytics（可选）
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# URL 结构
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"
future: true

# collections 原模板用于课程作业/讲义的组织，现在可以保留或忽略
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
